version: '3.1'
services:
 mysql:
  image: mysql:5.7.22
  environment:
   MYSQL_ROOT_PASSWORD: secret
  volumes:
   - ./datadir/mysql/:/var/lib/mysql

 app:
  build: .
  tty: true
  ports:
   - '4000:4000'
  volumes:
   - .:/app
  command: mix phx.server
  depends_on:
   - mysql
